const root=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bi=(th,en)=>`<span data-translated="1"><span class="th">${esc(th)}</span><span class="en">${esc(en)}</span></span>`;
const key='r4-pages-self-study-v1';let saved={done:[],answers:null,date:null};
try{const v=JSON.parse(localStorage.getItem(key));if(v&&Array.isArray(v.done))saved={...saved,...v};}catch{}
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));}catch{alert('บันทึกบนเบราว์เซอร์ไม่ได้ / Browser storage is unavailable.');}}
const page=new URLSearchParams(location.search).get('page')||'home';
const button=(th,en,p)=>`<a class="button" href="?page=${p}">${bi(th,en)}</a>`;
const done=()=>COURSE.modules.every(m=>saved.done.includes(m.id));
const answered=()=>saved.answers&&COURSE.assessment.questions.every(q=>q.options.some(o=>o.id===saved.answers[q.id]));
function nav(){return '<nav class="lessonnav">'+COURSE.modules.map(m=>button(m.id+(saved.done.includes(m.id)?' ✓':''),m.id+(saved.done.includes(m.id)?' ✓':''),m.id)).join('')+'</nav>';}
function home(){root.innerHTML=`<section class="intro"><h1>${bi('ทุกเที่ยว ทั้งคนขี่และคนซ้อน','Every trip, for riders and passengers')}</h1><p>${bi('เรียนรู้การเลือกหมวก ตรวจมาตรฐาน สวมให้พอดี และเตรียมพร้อมก่อนเดินทาง','Learn to select, check, fit and fasten your motorcycle helmet.')}</p><img src="static/campaign/safeguard-home-20261002.png" alt="Safeguard Khon Kaen"><p>${bi('ฉบับนี้ไม่เก็บชื่อหรือข้อมูลส่วนตัว ไม่ส่งผลเรียนให้โครงการ ความคืบหน้าจะอยู่เฉพาะเบราว์เซอร์นี้','This edition collects no names or personal profiles and sends no learning results to the project. Progress is stored only in this browser.')}</p>${nav()}${COURSE.modules.map(m=>`<section class="card"><h2>${esc(m.id)} · ${esc(m.title)}</h2><p>${esc(m.objective)}</p>${button('เปิดบทเรียน','Open lesson',m.id)}</section>`).join('')}</section>`;}
function lesson(id){root.innerHTML=nav()+LESSONS[id]+`<div class="actions"><button id="complete">${bi('อ่านบทนี้จบแล้ว','Mark lesson complete')}</button>${button('ทำแบบทดสอบ','Take the quiz','quiz')}</div>`;root.querySelector('#complete').onclick=()=>{if(!saved.done.includes(id))saved.done.push(id);persist();location.href='?page='+(id==='M5'?'quiz':'M'+(Number(id.slice(1))+1));};const d=root.querySelector('dialog');if(d){const v=d.querySelector('.viewer'),pic=v.querySelector('img'),z=d.querySelector('#zoom');root.querySelectorAll('[data-art]').forEach(b=>b.onclick=()=>{const img=root.querySelector('#'+b.dataset.art);pic.src=img.src;pic.alt=img.alt;v.classList.remove('zoom');d.showModal();});d.querySelector('#close').onclick=()=>d.close();z.onclick=()=>v.classList.toggle('zoom');}if(location.hash)requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());}
function quiz(){if(!done()){root.innerHTML=`<h1>${bi('แบบทดสอบ','Quiz')}</h1><p>${bi('กรุณาอ่านและกดจบบทเรียนให้ครบทั้ง 5 บทก่อน','Read and mark all five lessons complete first.')}</p>${nav()}`;return;}root.innerHTML=`<h1>${bi('ทบทวนความรู้ 10 ข้อ','Ten-question knowledge check')}</h1><p>${bi('ตรวจคำตอบบนเครื่องเพื่อฝึกเรียนรู้ ผลไม่ใช่คะแนนที่รับรองโดยโครงการ','Answers are checked on this device for practice. Results are not certified by the project.')}</p><form id="quiz">${COURSE.assessment.questions.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q.prompt)}</legend>${q.options.map(o=>`<label class="quiz-option"><input required type="radio" name="${esc(q.id)}" value="${o.id}" ${saved.answers?.[q.id]===o.id?'checked':''}><span>${esc(o.text)}</span></label>`).join('')}</fieldset>`).join('')}<button type="submit">${bi('ตรวจคำตอบ','Check answers')}</button></form><div id="result"></div>`;root.querySelector('#quiz').onsubmit=e=>{e.preventDefault();saved.answers=Object.fromEntries(new FormData(e.target));saved.date=new Date().toISOString();persist();showResults();};if(answered())showResults();}
function showResults(){const score=COURSE.assessment.questions.filter(q=>q.answer===saved.answers[q.id]).length;root.querySelector('#result').innerHTML=`<section class="card"><h2>${bi('คะแนนฝึกทำ','Practice score')}: ${score}/10</h2>${COURSE.assessment.questions.map(q=>`<p><b>${esc(q.prompt)}</b><br>${esc(q.answer)}. ${esc(q.options.find(o=>o.id===q.answer).text)}<br>${esc(q.feedback)}</p>`).join('')}${button('ดูใบประกาศตัวอย่าง','View sample certificate','certificate')}</section>`;}
function certificate(){if(!done()||!answered()){root.innerHTML=`<p>${bi('เรียนครบ 5 บทและตอบครบ 10 ข้อก่อนเปิดใบประกาศตัวอย่าง','Complete five lessons and answer all ten questions to view the sample certificate.')}</p>${nav()}${button('แบบทดสอบ','Quiz','quiz')}`;return;}root.innerHTML=`<p class="noprint">${bi('ตัวอย่างสำหรับฝึกใช้งาน ไม่มีเลขรับรองหรือการตรวจสอบจากฐานข้อมูลกลาง','Practice sample only. No certified ID or central verification is provided.')}</p><article class="sample-cert"><div class="logos">${['aip-tight.png','clean-2.png','clean-3.png','clean-4.png','clean-5.png','clean-6.png','traffic-restored-approved.png','clean-8.png'].map(f=>`<img src="static/partners/${f}" alt="Partner">`).join('')}</div><p>R4 Helmet Safety Learning Hub</p><h1>${bi('ใบประกาศตัวอย่าง','SAMPLE CERTIFICATE')}</h1><h2>${bi('ผู้เรียนทดลอง','Sample learner')}</h2><p>${bi('ได้ทำกิจกรรมเรียนรู้เรื่องการเลือกและใช้หมวกนิรภัย ผ่านฉบับเรียนรู้ด้วยตนเอง','Completed self-study activities on selecting and using a motorcycle helmet.')}</p><p>${bi('โครงการ Safeguard จังหวัดขอนแก่น','Safeguard project, Khon Kaen Province')}</p><p>${esc(new Date(saved.date).toLocaleDateString('en-GB'))}</p><strong>${bi('เอกสารตัวอย่าง — ไม่ใช่ใบประกาศที่โครงการรับรอง','SAMPLE ONLY — Not a project-certified certificate')}</strong></article><p class="noprint"><button id="print">${bi('พิมพ์ / บันทึก PDF','Print / Save PDF')}</button></p><p class="noprint">${bi('ในหน้าพิมพ์เลือก Save as PDF / A4 / แนวนอน และปิดหัว–ท้ายกระดาษ','In the print dialog choose Save as PDF, A4, landscape, and disable headers and footers.')}</p>`;root.querySelector('#print').onclick=()=>window.print();}
document.querySelector('#reset').onclick=()=>{if(confirm('ล้างความคืบหน้าบนเบราว์เซอร์นี้? / Clear local progress?')){localStorage.removeItem(key);location.href='?page=home';}};
if(LESSONS[page])lesson(page);else if(page==='quiz')quiz();else if(page==='certificate')certificate();else home();
